image: gcc

stages:
  - compile
  - test

compile:
  stage: compile
  script:
    - make

participant:
  stage: test
  script:
    - mkdir test_tmp
    - cp /home/cs367/p3/* test_tmp/
    - python3 test_tmp/mod_c.py participant.c
    - make
    - cd test_tmp
    - pytest --tb=short -vv --color=yes -s --show-capture=all --capture=fd test_par.py

observer:
  stage: test
  script:
    - mkdir test_tmp
    - cp /home/cs367/p3/* test_tmp/
    - python3 test_tmp/mod_c.py observer.c
    - make
    - cd test_tmp
    - pytest --tb=short -vv --color=yes -s --show-capture=all --capture=fd test_obs.py

server:
  stage: test
  script:
    - mkdir test_tmp
    - cp /home/cs367/p3/* test_tmp/
    - make
    - cd test_tmp
    - pytest --tb=short -vv --color=yes -s --show-capture=all --capture=fd test_ser.py
